### PR TITLE
Beta 8 compatibility

### PR DESCRIPTION
**Pull request by Ralkage**
- Added compatibility for beta 8.
- Added a LICENSE file because we like those in the Flarum community 👍
- Converted FA4 extension icon to FA5.

### CODE REVIEW

**Comment by piotr-tokarczyk** [comment]
Hi @Ralkage ,
Currently I don't have any free time to check if your PR works.
In some near future I'll try to find some time and merge it.

**Comment by Ralkage** [comment]
@piotr-tokarczyk your extension was requested by a few users to be updated for Beta 8 by the [FriendsOfFlarum initiative](https://github.com/FriendsOfFlarum). Do you care or mind if we transition this extension under FriendsOfFlarum so that we may push a Beta 8 compatibility update? FoF helps maintain extensions that developers either have no time for any more or haven't updated their extensions in quite some time.

Please let me know :)

**Comment by piotr-tokarczyk** [comment]
@Ralkage Please feel free to transit it. If you will need my help ask, I'll try to do my best.

**Comment by Ralkage** [comment]
Closing this PR as it was forked into a newer extension tackling beta 8 compatibility.

See: https://github.com/FriendsOfFlarum/default-user-preferences

**Pull request closed without merging**
